### ISSUE TITLE
mSPoC

### ISSUE THREAD

**Issue by xiaoshanhuang** [svendaehne/matlab_SPoC#1]
Hi  Sven,

When will mSPoC be available online? I would like to try it on my multimodal data if that is possible, even a beta version would be nice. Thanks!

**Comment by svendaehne** [comment]
Dear @xiaoshanhuang 
sorry for the late response. I am working on it but there are still some issues I need to adress before I can post the public version. 
Stay tuned! ;-)

**Comment by svendaehne** [comment]
mspoc code is now added. 

Let me know if you have troubles.
